from odoo import models, fields

class StockRule(models.Model):
    _inherit = 'stock.rule'

    separate_push_transfers = fields.Boolean(
        string="Create Separate Transfers",
        help="If enabled, each move generated by this push rule will use a unique procurement group to prevent merging into a single transfer."
    )

    def _push_prepare_move_copy_values(self, move_to_copy, new_date):
        res = super()._push_prepare_move_copy_values(move_to_copy, new_date)

        print(self.separate_push_transfers, self.name)
        if self.separate_push_transfers:
            group = self.env['procurement.group'].create({
                'name': f'Push - {move_to_copy.reference or move_to_copy.name or move_to_copy.id}',
            })
            res['group_id'] = group.id

        return res
