{
    'name': 'Stock Rule Push Separation Weenect LIT',
    'version': '1.0',
    'description': 'Adds an option to prevent the merging of transfers generated by push rules.',
    'summary': 'Stock Rule Push Separation Weenect LIT',
    'author': 'Limpid IT',
    'license': 'LGPL-3',
    'depends': [
        'stock'
    ],
    'data': [
        'views/stock_rule_views.xml',
    ],
    'auto_install': False,
    'application': False
}